FROM node as build
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
ENV REACT_APP_URL=https://tylergoh.com/api/
RUN npm run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/