version: "3.8"
services:
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
  node-server:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    env_file: ./env/node-server-dev.env
    volumes:
      - ./backend:/app
  mongo:
    image: mongo
    volumes: 
      - /mongodb/data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - "8080:8081"
    env_file: ./env/mongo-express.env
    restart: unless-stopped
  redis:
    image: redis
    restart: unless-stopped
