version: "3.8"
services:
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/letsencrypt/test:/letsencrypt/test:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
  node-server:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file: ./env/node-server-prod.env
  mongo:
    image: mongo
    volumes: 
      - /mongodb/data:/data/db
  redis:
    image: redis