version: "3.8"
services:
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    env_file: ./env/react.env
  node-server:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    env_file: ./env/node-server.env
  mongodb:
    image: mongo
    env_file: ./env/mongo-db.env
